export const _starters = [
  'Henrik Nässén',
  'Jonas Strandberg',
  'Filip Dolata',
  'Tom Chabousseau',
  'Mikael Pettersson',
  'Pelle Linusson',
  'Andreas Jonsson ?',
  'Freddy Jansson ? ',
  'Stefan Eldh',
  'Andreas Eldh',
  'Anders Eriksson',
  'Björn Johansson',
  'Andreas Lindberg ?',
  'Erik Högbom ?',
  'Erik Berner-Wik',
  'Lennart Chrona',
  'Abi',
  'Farzan Menhaj ?',
  'Felicia ?',
  'Roger Karlsson',
]
